PACKAGE_NAME="rust-out-of-tree"
PACKAGE_VERSION="0.1"
BUILT_MODULE_NAME[0]="rust_out_of_tree"
DEST_MODULE_LOCATION[0]="/updates/dkms"
MAKE[0]="make KDIR=${kernel_source_dir}"
CLEAN="make clean KDIR=${kernel_source_dir}"
AUTOINSTALL="yes"
